export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const LOGIN_SUCCESS_INS = "LOGIN_SUCCESS_INS";
export const USER_LOADED_INS = "USER_LOADED_INS";

export const SET_COURSEID = "SET_COURSEID";
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const COURSE_ERROR = 'COURSE_ERROR';
export const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS ';
export const UPDATE_TECHSTACK_SUCCESS = 'UPDATE_TECHSTACK_SUCCESS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const LOAD_CPROFILE_SUCCESS = 'LOAD_CPROFILE_SUCCESS'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const GET_COURSE_PROFILE = 'LOAD_CPROFILE_SUCCESS'

export const GET_POLL_BY_COURSE_ID = 'GET_POLL_BY_COURSE_ID'
export const LOAD_POLL_SUCCESS = 'LOAD_POLL_SUCCESS'
export const POLL_ERROR = 'POLL_ERROR'
export const ADD_POLL_SUCCESS = 'ADD_POLL_SUCCESS'
export const GET_POLL = 'GET_POLL'

export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS'
export const TEAM_ERROR = 'TEAM_ERROR'
export const LOAD_TEAM_SUCCESS = 'LOAD_TEAM_SUCCESS'
export const GET_TEAMS_BY_COURSE_ID = 'GET_TEAMS_BY_COURSE_ID'
